In [1]:
path = '../data/weather_data.json'
import json

import pandas as pd

pd.set_option('display.max_columns', None) # Configura o pandas para exibir todas as colunas do DataFrame, evitando que sejam truncadas na saída.
pd.set_option('display.max_rows', None) # Configura o pandas para exibir todas as linhas do DataFrame, evitando que sejam truncadas na saída.
pd.set_option('display.width', None) # Configura o pandas para ajustar a largura da saída de acordo com o conteúdo, evitando que as linhas sejam quebradas.
pd.set_option('display.max_colwidth', None) # Configura o pandas para exibir o conteúdo completo de cada célula, evitando que sejam truncados.


with open(path) as f:
    data = json.load(f) # Carrega os dados JSON do arquivo para a variável 'data', transformando o conteúdo do arquivo em um objeto Python (geralmente um dicionário ou uma lista, dependendo da estrutura do JSON).

print(data)

df = pd.json_normalize(data) # Normaliza os dados JSON em um DataFrame do pandas
df.head() # Exibe as primeiras linhas do DataFrame para verificar os dados(5 primeiras linhas)

{'coord': {'lon': -46.6361, 'lat': -23.5475}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'base': 'stations', 'main': {'temp': 296.24, 'feels_like': 296.33, 'temp_min': 295.35, 'temp_max': 297.29, 'pressure': 1013, 'humidity': 66, 'sea_level': 1013, 'grnd_level': 923}, 'visibility': 10000, 'wind': {'speed': 8.23, 'deg': 170}, 'clouds': {'all': 75}, 'dt': 1772391192, 'sys': {'type': 1, 'id': 8394, 'country': 'BR', 'sunrise': 1772355728, 'sunset': 1772400960}, 'timezone': -10800, 'id': 3448439, 'name': 'São Paulo', 'cod': 200}

,weather,base,visibility,dt,timezone,id,name,cod,coord.lon,coord.lat,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,main.humidity,main.sea_level,main.grnd_level,wind.speed,wind.deg,clouds.all,sys.type,sys.id,sys.country,sys.sunrise,sys.sunset
0,"[{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}]",stations,10000,1772391192,-10800,3448439,São Paulo,200,-46.6361,-23.5475,296.24,296.33,295.35,297.29,1013,66,1013,923,8.23,170,75,1,8394,BR,1772355728,1772400960

In [2]:
df.info() # Exibe informações sobre o DataFrame, como o número de entradas, tipos de dados e uso de memória.

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   weather          1 non-null      object
 1   base             1 non-null      str
 2   visibility       1 non-null      int64
 3   dt               1 non-null      int64
 4   timezone         1 non-null      int64
 5   id               1 non-null      int64
 6   name             1 non-null      str
 7   cod              1 non-null      int64
 8   coord.lon        1 non-null      float64
 9   coord.lat        1 non-null      float64
 10  main.temp        1 non-null      float64
 11  main.feels_like  1 non-null      float64
 12  main.temp_min    1 non-null      float64
 13  main.temp_max    1 non-null      float64
 14  main.pressure    1 non-null      int64
 15  main.humidity    1 non-null      int64
 16  main.sea_level   1 non-null      int64
 17  main.grnd_level  1 non-null      int64
 18  wind.speed       1 non-null      float64
 19  wind.deg         1 non-null      int64
 20  clouds.all       1 non-null      int64
 21  sys.type         1 non-null      int64
 22  sys.id           1 non-null      int64
 23  sys.country      1 non-null      str
 24  sys.sunrise      1 non-null      int64
 25  sys.sunset       1 non-null      int64
dtypes: float64(7), int64(15), object(1), str(3)
memory usage: 340.0+ bytes

In [ ]:
import pandas as pd
from pathlib import Path
import json
import logging
# Configura o logging para exibir mensagens de informação com um formato específico, incluindo a data e hora, o nível de log e a mensagem.
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Define o caminho para o arquivo JSON contendo os dados meteorológicos, utilizando a biblioteca Path para construir o caminho de forma portátil e segura.
# O caminho é construído a partir do diretório do arquivo atual (__file__), subindo um nível (parent), e depois navegando para a pasta 'data' e o arquivo 'weather_data.json'.
#path_name = Path(__file__).parent.parent / 'data' / 'weather_data.json'

path_name = Path('../data/weather_data.json')


def create_dataframe(path_name: str)  -> pd.DataFrame:
    """Cria um DataFrame a partir de um arquivo JSON.
        Args:
            path (str): O caminho para o arquivo JSON.

        Returns:
            pd.DataFrame: Um DataFrame contendo os dados do arquivo JSON.
        """
    logging.info(f"Criando DataFRame do arquivo JSON...")
    path = path_name

    if not path.exists():
        raise FileNotFoundError(f"Arquivo não encontrado: {path}")
    
    with open(path) as f:
        data = json.load(f)
    
    df = pd.json_normalize(data)
    logging.info(f"DataFrame criado com sucesso. Número de linhas: {len(df)}, Número de colunas: {len(df.columns)}")
    return df

#create_dataframe(path_name)

2026-03-02 10:36:51,171 - INFO - Criando DataFRame do arquivo JSON...
2026-03-02 10:36:51,176 - INFO - DataFrame criado com sucesso. Número de linhas: 1, Número de colunas: 26

,weather,base,visibility,dt,timezone,id,name,cod,coord.lon,coord.lat,...,main.sea_level,main.grnd_level,wind.speed,wind.deg,clouds.all,sys.type,sys.id,sys.country,sys.sunrise,sys.sunset
0,"[{'id': 803, 'main': 'Clouds', 'description': ...",stations,10000,1772391192,-10800,3448439,São Paulo,200,-46.6361,-23.5475,...,1013,923,8.23,170,75,1,8394,BR,1772355728,1772400960

In [15]:
import pandas as pd
from pathlib import Path
import json
import logging
# Configura o logging para exibir mensagens de informação com um formato específico, incluindo a data e hora, o nível de log e a mensagem.
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Define o caminho para o arquivo JSON contendo os dados meteorológicos, utilizando a biblioteca Path para construir o caminho de forma portátil e segura.
# O caminho é construído a partir do diretório do arquivo atual (__file__), subindo um nível (parent), e depois navegando para a pasta 'data' e o arquivo 'weather_data.json'.
#path_name = Path(__file__).parent.parent / 'data' / 'weather_data.json'

path_name = Path('../data/weather_data.json')


def create_dataframe(path_name: str)  -> pd.DataFrame:
    """Cria um DataFrame a partir de um arquivo JSON.
        Args:
            path (str): O caminho para o arquivo JSON.

        Returns:
            pd.DataFrame: Um DataFrame contendo os dados do arquivo JSON.
        """
    logging.info(f"Criando DataFRame do arquivo JSON...")
    path = path_name

    if not path.exists():
        raise FileNotFoundError(f"Arquivo não encontrado: {path}")
    
    with open(path) as f:
        data = json.load(f)
    
    df = pd.json_normalize(data)
    logging.info(f"DataFrame criado com sucesso. Número de linhas: {len(df)}, Número de colunas: {len(df.columns)}")
    return df

def normalize_weather_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Normaliza os nomes das colunas do DataFrame de dados meteorológicos.
        Args:
            df (pd.DataFrame): O DataFrame a ser normalizado.

        Returns:
            pd.DataFrame: Um DataFrame com os nomes das colunas normalizados.
        """
    df_weather = pd.json_normalize(df['weather'].apply(lambda x: x[0])) # Normaliza a coluna 'weather' do DataFrame, aplicando uma função lambda para extrair o primeiro elemento de cada lista na coluna 'weather' e criando um novo DataFrame com os dados normalizados.
    
    df_weather = df_weather.rename(columns={
        'id' : 'weather_id',
        'main' : 'weather_main',
        'description' : 'weather_description',
        'icon' : 'weather_icon'
    }
    )

    df = pd.concat([df, df_weather], axis=1) # Concatena o DataFrame original com o DataFrame normalizado 'df_weather' ao longo do eixo das colunas (axis=1), resultando em um DataFrame combinado que inclui as colunas originais e as novas colunas normalizadas.

    logging.info(f"\n/ Coluna 'weather' normalizada com sucesso. Número de colunas após normalização: {len(df.columns)}")
    return df

df = create_dataframe(path_name)
df = normalize_weather_columns(df)

df.head()
#df = normalize_weather_columns(df)
#print(df.head())
#create_dataframe(path_name)

2026-03-02 11:26:54,437 - INFO - Criando DataFRame do arquivo JSON...
2026-03-02 11:26:54,439 - INFO - DataFrame criado com sucesso. Número de linhas: 1, Número de colunas: 26
2026-03-02 11:26:54,441 - INFO -
/ Coluna 'weather' normalizada com sucesso. Número de colunas após normalização: 30

,weather,base,visibility,dt,timezone,id,name,cod,coord.lon,coord.lat,...,clouds.all,sys.type,sys.id,sys.country,sys.sunrise,sys.sunset,weather_id,weather_main,weather_description,weather_icon
0,"[{'id': 803, 'main': 'Clouds', 'description': ...",stations,10000,1772391192,-10800,3448439,São Paulo,200,-46.6361,-23.5475,...,75,1,8394,BR,1772355728,1772400960,803,Clouds,broken clouds,04d

In [1]:
import pandas as pd
from pathlib import Path
import json
import logging
# Configura o logging para exibir mensagens de informação com um formato específico, incluindo a data e hora, o nível de log e a mensagem.
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Define o caminho para o arquivo JSON contendo os dados meteorológicos, utilizando a biblioteca Path para construir o caminho de forma portátil e segura.
# O caminho é construído a partir do diretório do arquivo atual (__file__), subindo um nível (parent), e depois navegando para a pasta 'data' e o arquivo 'weather_data.json'.
#path_name = Path(__file__).parent.parent / 'data' / 'weather_data.json'

path_name = Path('../data/weather_data.json')
columns_name_to_drop = ['weather','weather_icon','sys.type']

def create_dataframe(path_name: str)  -> pd.DataFrame:
    """Cria um DataFrame a partir de um arquivo JSON.
        Args:
            path (str): O caminho para o arquivo JSON.

        Returns:
            pd.DataFrame: Um DataFrame contendo os dados do arquivo JSON.
        """
    logging.info(f"Criando DataFRame do arquivo JSON...")
    path = path_name

    if not path.exists():
        raise FileNotFoundError(f"Arquivo não encontrado: {path}")
    
    with open(path) as f:
        data = json.load(f)
    
    df = pd.json_normalize(data)
    logging.info(f"DataFrame criado com sucesso. Número de linhas: {len(df)}, Número de colunas: {len(df.columns)}")
    return df

def normalize_weather_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Normaliza os nomes das colunas do DataFrame de dados meteorológicos.
        Args:
            df (pd.DataFrame): O DataFrame a ser normalizado.

        Returns:
            pd.DataFrame: Um DataFrame com os nomes das colunas normalizados.
        """
    df_weather = pd.json_normalize(df['weather'].apply(lambda x: x[0])) # Normaliza a coluna 'weather' do DataFrame, aplicando uma função lambda para extrair o primeiro elemento de cada lista na coluna 'weather' e criando um novo DataFrame com os dados normalizados.
    
    df_weather = df_weather.rename(columns={
        'id' : 'weather_id',
        'main' : 'weather_main',
        'description' : 'weather_description',
        'icon' : 'weather_icon'
    }
    )

    df = pd.concat([df, df_weather], axis=1) # Concatena o DataFrame original com o DataFrame normalizado 'df_weather' ao longo do eixo das colunas (axis=1), resultando em um DataFrame combinado que inclui as colunas originais e as novas colunas normalizadas.

    logging.info(f"\n/ Coluna 'weather' normalizada com sucesso. Número de colunas após normalização: {len(df.columns)}")
    return df

def drop_weather_column(df: pd.DataFrame, columns_name: list[str]) -> pd.DataFrame:
    logging.info(f"Removendo coluna {columns_name}")
    df = df.drop(columns=columns_name)
    logging.info(f"Colunas {columns_name} removidas com sucesso.")
    return df

df = create_dataframe(path_name)
df = normalize_weather_columns(df)
df = drop_weather_column(df, columns_name_to_drop)
df.head()

2026-03-02 14:45:44,876 - INFO - Criando DataFRame do arquivo JSON...
2026-03-02 14:45:44,878 - INFO - DataFrame criado com sucesso. Número de linhas: 1, Número de colunas: 26
2026-03-02 14:45:44,882 - INFO -
/ Coluna 'weather' normalizada com sucesso. Número de colunas após normalização: 30
2026-03-02 14:45:44,883 - INFO - Removendo coluna ['weather', 'weather_icon', 'sys.type']
2026-03-02 14:45:44,884 - INFO - Colunas ['weather', 'weather_icon', 'sys.type'] removidas com sucesso.

,base,visibility,dt,timezone,id,name,cod,coord.lon,coord.lat,main.temp,...,wind.speed,wind.deg,clouds.all,sys.id,sys.country,sys.sunrise,sys.sunset,weather_id,weather_main,weather_description
0,stations,10000,1772391192,-10800,3448439,São Paulo,200,-46.6361,-23.5475,296.24,...,8.23,170,75,8394,BR,1772355728,1772400960,803,Clouds,broken clouds

In [2]:
import pandas as pd
from pathlib import Path
import json
import logging
# Configura o logging para exibir mensagens de informação com um formato específico, incluindo a data e hora, o nível de log e a mensagem.
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Define o caminho para o arquivo JSON contendo os dados meteorológicos, utilizando a biblioteca Path para construir o caminho de forma portátil e segura.
# O caminho é construído a partir do diretório do arquivo atual (__file__), subindo um nível (parent), e depois navegando para a pasta 'data' e o arquivo 'weather_data.json'.
#path_name = Path(__file__).parent.parent / 'data' / 'weather_data.json'

path_name = Path('../data/weather_data.json')
columns_name_to_drop = ['weather','weather_icon','sys.type']
columns_name_to_rename = {
    "base" : "base",
    "visibility" : "visibility",
    "dt" : "datetime",
    "timezone" : "timezone",    
    "id" : "city_id",
    "name" : "city_name",
    "code" : "code",
    "coord.lon" : "longitude",
    "coord.lat" : "latitude",
    "main.temp" : "temperature",
    "main.feels_like" : "feels_like",
    "main.temp_min" : "temp_min",
    "main.temp_max" : "temp_max",
    "main.pressure" : "pressure",
    "main.humidity" : "humidity",
    "main.sea_level" : "sea_level",
    "main.grnd_level" : "grnd_level",
    "wind.speed" : "wind_speed",
    "wind.deg" : "wind_deg",
    "wind.gust" : "wind_gust",
    "clouds.all" : "clouds",
    "sys.type" : "sys_type",
    "sys.id" : "sys_id",
    "sys.country" : "country",
    "sys.sunrise" : "sunrise",
    "sys.sunset" : "sunset"
}


def create_dataframe(path_name: str)  -> pd.DataFrame:
    """Cria um DataFrame a partir de um arquivo JSON.
        Args:
            path (str): O caminho para o arquivo JSON.

        Returns:
            pd.DataFrame: Um DataFrame contendo os dados do arquivo JSON.
        """
    logging.info(f"Criando DataFRame do arquivo JSON...")
    path = path_name

    if not path.exists():
        raise FileNotFoundError(f"Arquivo não encontrado: {path}")
    
    with open(path) as f:
        data = json.load(f)
    
    df = pd.json_normalize(data)
    logging.info(f"DataFrame criado com sucesso. Número de linhas: {len(df)}, Número de colunas: {len(df.columns)}")
    return df

def normalize_weather_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Normaliza os nomes das colunas do DataFrame de dados meteorológicos.
        Args:
            df (pd.DataFrame): O DataFrame a ser normalizado.

        Returns:
            pd.DataFrame: Um DataFrame com os nomes das colunas normalizados.
        """
    df_weather = pd.json_normalize(df['weather'].apply(lambda x: x[0])) # Normaliza a coluna 'weather' do DataFrame, aplicando uma função lambda para extrair o primeiro elemento de cada lista na coluna 'weather' e criando um novo DataFrame com os dados normalizados.
    
    df_weather = df_weather.rename(columns={
        'id' : 'weather_id',
        'main' : 'weather_main',
        'description' : 'weather_description',
        'icon' : 'weather_icon'
    }
    )

    df = pd.concat([df, df_weather], axis=1) # Concatena o DataFrame original com o DataFrame normalizado 'df_weather' ao longo do eixo das colunas (axis=1), resultando em um DataFrame combinado que inclui as colunas originais e as novas colunas normalizadas.

    logging.info(f"\n/ Coluna 'weather' normalizada com sucesso. Número de colunas após normalização: {len(df.columns)}")
    return df

def drop_weather_column(df: pd.DataFrame, columns_name: list[str]) -> pd.DataFrame:
    logging.info(f"Removendo coluna {columns_name}")
    df = df.drop(columns=columns_name)
    logging.info(f"Colunas {columns_name} removidas com sucesso.")
    return df

def rename_columns(df: pd.DataFrame, columns_name: dict[str:str]) -> pd.DataFrame:
    logging.info(f"Renomeando colunas {columns_name}")
    df = df.rename(columns=columns_name)
    logging.info(f"Colunas {list(columns_name.values())} renomeadas com sucesso.")
    return df

df = create_dataframe(path_name)
df = normalize_weather_columns(df)
df = drop_weather_column(df, columns_name_to_drop)
df = rename_columns(df, columns_name_to_rename)
df.head()

2026-03-02 14:58:47,560 - INFO - Criando DataFRame do arquivo JSON...
2026-03-02 14:58:47,562 - INFO - DataFrame criado com sucesso. Número de linhas: 1, Número de colunas: 26
2026-03-02 14:58:47,564 - INFO -
/ Coluna 'weather' normalizada com sucesso. Número de colunas após normalização: 30
2026-03-02 14:58:47,565 - INFO - Removendo coluna ['weather', 'weather_icon', 'sys.type']
2026-03-02 14:58:47,567 - INFO - Colunas ['weather', 'weather_icon', 'sys.type'] removidas com sucesso.
2026-03-02 14:58:47,567 - INFO - Renomeando colunas {'base': 'base', 'visibility': 'visibility', 'dt': 'datetime', 'timezone': 'timezone', 'id': 'city_id', 'name': 'city_name', 'code': 'code', 'coord.lon': 'longitude', 'coord.lat': 'latitude', 'main.temp': 'temperature', 'main.feels_like': 'feels_like', 'main.temp_min': 'temp_min', 'main.temp_max': 'temp_max', 'main.pressure': 'pressure', 'main.humidity': 'humidity', 'main.sea_level': 'sea_level', 'main.grnd_level': 'grnd_level', 'wind.speed': 'wind_speed', 'wind.deg': 'wind_deg', 'wind.gust': 'wind_gust', 'clouds.all': 'clouds', 'sys.type': 'sys_type', 'sys.id': 'sys_id', 'sys.country': 'country', 'sys.sunrise': 'sunrise', 'sys.sunset': 'sunset'}
2026-03-02 14:58:47,569 - INFO - Colunas ['base', 'visibility', 'datetime', 'timezone', 'city_id', 'city_name', 'code', 'longitude', 'latitude', 'temperature', 'feels_like', 'temp_min', 'temp_max', 'pressure', 'humidity', 'sea_level', 'grnd_level', 'wind_speed', 'wind_deg', 'wind_gust', 'clouds', 'sys_type', 'sys_id', 'country', 'sunrise', 'sunset'] renomeadas com sucesso.

,base,visibility,datetime,timezone,city_id,city_name,cod,longitude,latitude,temperature,...,wind_speed,wind_deg,clouds,sys_id,country,sunrise,sunset,weather_id,weather_main,weather_description
0,stations,10000,1772391192,-10800,3448439,São Paulo,200,-46.6361,-23.5475,296.24,...,8.23,170,75,8394,BR,1772355728,1772400960,803,Clouds,broken clouds

In [4]:
import pandas as pd
from pathlib import Path
import json
import logging
# Configura o logging para exibir mensagens de informação com um formato específico, incluindo a data e hora, o nível de log e a mensagem.
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Define o caminho para o arquivo JSON contendo os dados meteorológicos, utilizando a biblioteca Path para construir o caminho de forma portátil e segura.
# O caminho é construído a partir do diretório do arquivo atual (__file__), subindo um nível (parent), e depois navegando para a pasta 'data' e o arquivo 'weather_data.json'.
#path_name = Path(__file__).parent.parent / 'data' / 'weather_data.json'

path_name = Path('../data/weather_data.json')
columns_name_to_drop = ['weather','weather_icon','sys.type']
columns_name_to_rename = {
    "base" : "base",
    "visibility" : "visibility",
    "dt" : "datetime",
    "timezone" : "timezone",    
    "id" : "city_id",
    "name" : "city_name",
    "code" : "code",
    "coord.lon" : "longitude",
    "coord.lat" : "latitude",
    "main.temp" : "temperature",
    "main.feels_like" : "feels_like",
    "main.temp_min" : "temp_min",
    "main.temp_max" : "temp_max",
    "main.pressure" : "pressure",
    "main.humidity" : "humidity",
    "main.sea_level" : "sea_level",
    "main.grnd_level" : "grnd_level",
    "wind.speed" : "wind_speed",
    "wind.deg" : "wind_deg",
    "wind.gust" : "wind_gust",
    "clouds.all" : "clouds",
    "sys.type" : "sys_type",
    "sys.id" : "sys_id",
    "sys.country" : "country",
    "sys.sunrise" : "sunrise",
    "sys.sunset" : "sunset"
}

columns_to_normalize_datetime = ['datetime','sunrise','sunset']

def create_dataframe(path_name: str)  -> pd.DataFrame:
    """Cria um DataFrame a partir de um arquivo JSON.
        Args:
            path (str): O caminho para o arquivo JSON.

        Returns:
            pd.DataFrame: Um DataFrame contendo os dados do arquivo JSON.
        """
    logging.info(f"Criando DataFRame do arquivo JSON...")
    path = path_name

    if not path.exists():
        raise FileNotFoundError(f"Arquivo não encontrado: {path}")
    
    with open(path) as f:
        data = json.load(f)
    
    df = pd.json_normalize(data)
    logging.info(f"DataFrame criado com sucesso. Número de linhas: {len(df)}, Número de colunas: {len(df.columns)}")
    return df

def normalize_weather_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Normaliza os nomes das colunas do DataFrame de dados meteorológicos.
        Args:
            df (pd.DataFrame): O DataFrame a ser normalizado.

        Returns:
            pd.DataFrame: Um DataFrame com os nomes das colunas normalizados.
        """
    df_weather = pd.json_normalize(df['weather'].apply(lambda x: x[0])) # Normaliza a coluna 'weather' do DataFrame, aplicando uma função lambda para extrair o primeiro elemento de cada lista na coluna 'weather' e criando um novo DataFrame com os dados normalizados.
    
    df_weather = df_weather.rename(columns={
        'id' : 'weather_id',
        'main' : 'weather_main',
        'description' : 'weather_description',
        'icon' : 'weather_icon'
    }
    )

    df = pd.concat([df, df_weather], axis=1) # Concatena o DataFrame original com o DataFrame normalizado 'df_weather' ao longo do eixo das colunas (axis=1), resultando em um DataFrame combinado que inclui as colunas originais e as novas colunas normalizadas.

    logging.info(f"\n/ Coluna 'weather' normalizada com sucesso. Número de colunas após normalização: {len(df.columns)}")
    return df

def drop_weather_column(df: pd.DataFrame, columns_name: list[str]) -> pd.DataFrame:
    logging.info(f"Removendo coluna {columns_name}")
    df = df.drop(columns=columns_name)
    logging.info(f"Colunas {columns_name} removidas com sucesso.")
    return df

def rename_columns(df: pd.DataFrame, columns_name: dict[str:str]) -> pd.DataFrame:
    logging.info(f"Renomeando colunas {columns_name}")
    df = df.rename(columns=columns_name)
    logging.info(f"Colunas {list(columns_name.values())} renomeadas com sucesso.")
    return df

def normalize_datetime_columns(df: pd.DataFrame, columns_name: list[str]) -> pd.DataFrame:

    for name in columns_name:
        logging.info(f"Normalizando coluna de data/hora: {name}")
        df[name] = pd.to_datetime(df[name], unit='s',utc=True).dt.tz_convert('America/Sao_Paulo')# Converte a coluna de data/hora para o formato datetime do pandas, especificando que os valores estão em segundos (unit='s') e que estão em UTC (utc=True), e depois converte para o fuso horário 'America/Sao_Paulo' usando dt.tz_convert().
        logging.info(f"Coluna {name} normalizada com sucesso.")
    return df

def data_transformation():
    print("Iniciando transformação dos dados...")
    df = create_dataframe(path_name)
    df = normalize_weather_columns(df)
    df = drop_weather_column(df, columns_name_to_drop)
    df = rename_columns(df, columns_name_to_rename)
    df = normalize_datetime_columns(df, columns_to_normalize_datetime)
    print("Transformação dos dados concluída.")
    return df
data_transformation()

2026-03-02 15:17:20,490 - INFO - Criando DataFRame do arquivo JSON...
2026-03-02 15:17:20,501 - INFO - DataFrame criado com sucesso. Número de linhas: 1, Número de colunas: 26
2026-03-02 15:17:20,504 - INFO -
/ Coluna 'weather' normalizada com sucesso. Número de colunas após normalização: 30
2026-03-02 15:17:20,505 - INFO - Removendo coluna ['weather', 'weather_icon', 'sys.type']
2026-03-02 15:17:20,507 - INFO - Colunas ['weather', 'weather_icon', 'sys.type'] removidas com sucesso.
2026-03-02 15:17:20,508 - INFO - Renomeando colunas {'base': 'base', 'visibility': 'visibility', 'dt': 'datetime', 'timezone': 'timezone', 'id': 'city_id', 'name': 'city_name', 'code': 'code', 'coord.lon': 'longitude', 'coord.lat': 'latitude', 'main.temp': 'temperature', 'main.feels_like': 'feels_like', 'main.temp_min': 'temp_min', 'main.temp_max': 'temp_max', 'main.pressure': 'pressure', 'main.humidity': 'humidity', 'main.sea_level': 'sea_level', 'main.grnd_level': 'grnd_level', 'wind.speed': 'wind_speed', 'wind.deg': 'wind_deg', 'wind.gust': 'wind_gust', 'clouds.all': 'clouds', 'sys.type': 'sys_type', 'sys.id': 'sys_id', 'sys.country': 'country', 'sys.sunrise': 'sunrise', 'sys.sunset': 'sunset'}
2026-03-02 15:17:20,510 - INFO - Colunas ['base', 'visibility', 'datetime', 'timezone', 'city_id', 'city_name', 'code', 'longitude', 'latitude', 'temperature', 'feels_like', 'temp_min', 'temp_max', 'pressure', 'humidity', 'sea_level', 'grnd_level', 'wind_speed', 'wind_deg', 'wind_gust', 'clouds', 'sys_type', 'sys_id', 'country', 'sunrise', 'sunset'] renomeadas com sucesso.
2026-03-02 15:17:20,511 - INFO - Normalizando coluna de data/hora: datetime
2026-03-02 15:17:20,514 - INFO - Coluna datetime normalizada com sucesso.
2026-03-02 15:17:20,515 - INFO - Normalizando coluna de data/hora: sunrise
2026-03-02 15:17:20,517 - INFO - Coluna sunrise normalizada com sucesso.
2026-03-02 15:17:20,517 - INFO - Normalizando coluna de data/hora: sunset
2026-03-02 15:17:20,519 - INFO - Coluna sunset normalizada com sucesso.

Iniciando transformação dos dados...
Transformação dos dados concluída.

,base,visibility,datetime,timezone,city_id,city_name,cod,longitude,latitude,temperature,...,wind_speed,wind_deg,clouds,sys_id,country,sunrise,sunset,weather_id,weather_main,weather_description
0,stations,10000,2026-03-01 15:53:12-03:00,-10800,3448439,São Paulo,200,-46.6361,-23.5475,296.24,...,8.23,170,75,8394,BR,2026-03-01 06:02:08-03:00,2026-03-01 18:36:00-03:00,803,Clouds,broken clouds